services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow 
    volumes:
      - C:/DockerVolumes/postgres/data:/var/lib/postgresql/data
    ports:
      - '3021:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dbt-network
    command: >
      postgres -c listen_addresses='*' 
              -c work_mem=1GB 
              -c maintenance_work_mem=3GB
              -c shared_buffers=2GB
              -c statement_timeout=0

  airflow-init:
    image: apache/airflow:2.7.1
    entrypoint: /bin/bash
    command: -c 'airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@admin.com'
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbt-network
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data


  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
        - postgres
        - airflow-init

    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq4wwjZsFN6J_MKuPcHVD4mwTk8qGf4M=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=FB0o_zt4e3Ziq4wwjZsFN6J_MKuPcHVD4mwTk8qGf4M=
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    ports:
      - "2001:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dbt-network

  airflow-scheduler:
    image: apache/airflow:2.7.1
    mem_limit: 4g
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq4wwjZsFN6J_MKuPcHVD4mwTk8qGf4M=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC=60
      - AIRFLOW__SCHEDULER__PROCESSOR_POLL_INTERVAL=10
      - AIRFLOW__CORE__TASK_EXECUTION_TIMEOUT=3600 
      - AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=2 
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    command: scheduler
    networks:
      - dbt-network

  dbt:
      build:
        context: ./dbt
      container_name: airflow_dbt 
      depends_on:
        - postgres
      networks:
        - dbt-network
      volumes:
        - ./dbt:/usr/app
      ports:
        - "2000:4000"
      environment:
        DBT_PROFILES_DIR: /usr/app

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "3020:80"
    depends_on:
      - postgres
    networks:
      - dbt-network

networks:
  dbt-network:
    driver: bridge
  postgres-data: 
    driver: local